# Generated by Django 4.1.5 on 2023-01-28 13:58

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManiPadiType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Mani/Padi Tpye',
                'verbose_name_plural': 'Mani/Padi Types',
            },
        ),
        migrations.CreateModel(
            name='NailType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Nail Type',
                'verbose_name_plural': 'Nail Types',
            },
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Service Type',
                'verbose_name_plural': 'Service Types',
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=6, max_length=6, prefix='', primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True)),
                ('special_request', models.TextField(blank=True, max_length=300, null=True)),
                ('has_allergies', models.BooleanField(default=False)),
                ('preferred_date_time', models.DateTimeField()),
                ('preferred_location', models.CharField(choices=[('home_service', 'Home Service'), ('walk_in', 'Walk - In Service')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('mani_padi_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.manipaditype')),
                ('nail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.nailtype')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.servicetype')),
            ],
        ),
    ]
